### ISSUE TITLE
A better webcam?

### ISSUE THREAD

**Issue by danott** [chantastic/ama#9]
How deep have you gone down the “DSLR or equivalent with clean HDMI out as web cam” rabbit hole?

If you were doing a fresh setup today, what camera, microphone, and dongles would you buy?

Affiliate links welcome! 🙂

**Comment by chantastic** [comment]
Dan!

First, I love you. Thanks for being my friend.

### Preference disclosure

My preference is for gear the "just works".
You might be able to get "this plus that" by implementing a firmware hack or getting the right aftermarket adapter...

I'm not into that.

I also like to find the minimum viable product that does what I need.
I don't like throwing money at a problem but I'm happy to spend as much as is required.

So, this is what I see as the "sweet spot" in early 2020.

## Best mirrorless camera for streaming video

The Sony [⍺6400 with kit lens](https://amzn.to/34eR4xG) is the best bang for buck.
This mirrorless camera can do everything a streamer wants out-of-the-box:
* Unlimited record time
* USB-power during operation
* Clean HDMI out
* A flip-up display — which is very handy for framing (even if the display goes blank during recording)

### More on the ⍺6400 line

The ⍺6000 line is opaque.
The ⍺6000, ⍺6300, and ⍺6500 were released in 2016.
They were replaced by the [⍺6100](https://amzn.to/2wjRZ3e), [⍺6400](https://amzn.to/34eR4xG), and [⍺6600](https://amzn.to/2yESK7X) (respectively) in 2019.

Only the 2019 models have *all* of the features mentioned above (without firmware hacks).

My money is on the [⍺6400 w/kit lens](https://amzn.to/34eR4xG).

The major gains of [⍺6600](https://amzn.to/2yESK7X) are in handheld ergonomics and battery life — which are extraneous for a streaming setup. And — at the price — you're edging into [Lumix GH5](https://amzn.to/2UI9kMx) territory, which is a fully capable video production camera.

The [⍺6100 w/kit lens](https://amzn.to/2wjRZ3e) may be a good way to save $150.
I'd read [this article](https://mirrorlesscomparison.com/preview/sony-a6100-vs-a6400-vs-a6600/) and any of the countless [comparison videos on YouTube](https://www.youtube.com/results?search_query=a6100+vs+6400).

### My personal blunders

I use a [Canon m50](https://amzn.to/3aXk0MQ) for video, which I do not recommend.

I got it because I like Canon's color science and I wanted a fully articulating display.
But it's a terrible streaming camera.
Canon cameras can't be operated on usb power.
So I have to remember to charge and change batteries between hour-long session.

Laughably, that fully articulating is inoperable during HDMI-streaming.

There's also no setting to bypass the 30-minute auto-shutoff.
I had to download some crappy tethering software to keep the camera operational during streaming.

Live and learn.

## Best mic

Last year, I wrote [a little tribute to my favorite budget microphone](http://shutupandstarttalking.com), the [Samson Q2U](https://amzn.to/2UIkGjM).
I know at least 10 people who have purchased the mic since and all have been pleased with it.

At ~$60, nothing else comes close but I have other recommendations at the $200.
I'm happy to follow up if that would be in-budget.

## Dongles and accessories

I use the [Elgato Cam Link 4k](https://www.elgato.com/en/gaming/cam-link-4k) to convert the HDMI signal to USB.
(It seems to be sold out right now 😬)

I use a [short microphone boom rm](https://amzn.to/2UIceAV) with [this camera to mic-stand adapter](https://amzn.to/34dFu5H) to set the camera right behind my monitor.

I use the [Elgato Key Light](https://www.elgato.com/en/gaming/key-light) to light myself.
There's also a lamp version: [Elgato Key Light Air](https://amzn.to/2yD1ATx).
Before that I used a crappy LED lamp 😅
The Elgato Key Light is great because it has an adjustable color temp and integrates wirelessly with my Mac and [Elgato Stream Deck XL](https://amzn.to/2JHnvuZ)

---

That's everything I can think of.

I hope it all helps!

_* Amazon links are affiliate links_
